### ISSUE TITLE
Playback time not returning to clock time

### ISSUE THREAD

**Issue by roidy** [arthur-liberman/service.openvfd#2]
If you have the addon set to display any of the playback time options and 'Display for' set to 'Always' then if the video/music that is playing ends naturally ie. it gets to the end and you don't press stop then the display never returns to the clock and you have to disable and re-enable the addon to fix it. If however you stop the playback using the 'Stop' button then the display returns to the clock as expected.

**Comment by arthur-liberman** [comment]
Thanks for reporting. I just pushed a fix for it - a4d229f.
