### ISSUE TITLE
building for kernel >= 5.0

### ISSUE THREAD

**Issue by rossbcan** [arthur-liberman/service.openvfd#6]
LibreELEC has patches

https://github.com/LibreELEC/linux_openvfd/commit/672de0dabdcc2b6aaf1086874437d06138e3f769

**Comment by arthur-liberman** [comment]
Not sure what this is about. This repository is for the OpenVFD Kodi addon, not the linux driver.
Besides, that commit was originally PRed to my repository by kszaq, and later cherry picked by chewitt.

**Comment by rossbcan** [comment]
Hi Arthur;

 

The “issue” is an FYI…

The API for one of the kernel calls (see link) changed for kernel > 5

I have not tested without patch to see what, if anything breaks. Want me to?

 

…B

**Comment by arthur-liberman** [comment]
It's already in the repo
https://github.com/arthur-liberman/linux_openvfd/pull/1
